clients:
  - clientId: gateway-client
    name: Gateway Client
    description: Client with use of reverse proxy from kong
    protocol: openid-connect
    publicClient: false
    secret: GATEWAY_SECRET
    redirectUris:
      - https://DHOSTNAME:PORT_GATEWAY/*
      - https://DHOSTNAME/*
    protocolMappers:
      - name: "groups"
        protocol: "openid-connect"
        protocolMapper: "oidc-group-membership-mapper"
        config:
          claim.name: "groups"
          full.path: "false"
          userinfo.token.claim: "true"
          id.token.claim: "true"
          access.token.claim: "true"
  - clientId: frontend-client
    name: Frontend Client
    description: Client for Frontend without client-authentication flow
    protocol: openid-connect
    publicClient: true
    redirectUris:
      - https://DHOSTNAME:PORT_GATEWAY/*
      - https://DHOSTNAME/*
      - http://localhost:4200/*
    protocolMappers:
      - name: "groups"
        protocol: "openid-connect"
        protocolMapper: "oidc-group-membership-mapper"
        config:
          claim.name: "groups"
          full.path: "false"
          userinfo.token.claim: "true"
          id.token.claim: "true"
          access.token.claim: "true"
    attributes:
      frontchannel.logout.url: "https://DHOSTNAME/red/oidc-frontchannel-logout.html"
    frontchannelLogout: "true"
  - clientId: nodered-client
    name: Node-Red Client
    description: ""
    protocol: openid-connect
    publicClient: false
    secret: NODE_RED_SECRET
    serviceAccountsEnabled: true
    implicitFlowEnabled: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    redirectUris:
      - /*
  - clientId: user-client
    name: user-client
    description: ""
    protocol: openid-connect
    publicClient: false
    secret: USER_SECRET
    serviceAccountsEnabled: true
    implicitFlowEnabled: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    redirectUris:
      - /*
    protocolMappers:
      - name: "groups"
        protocol: "openid-connect"
        protocolMapper: "oidc-group-membership-mapper"
        config:
          claim.name: "groups"
          full.path: "false"
          userinfo.token.claim: "true"
          id.token.claim: "true"
          access.token.claim: "true"
