clientScopes:
  - name: "roles"
    protocol: "openid-connect"
    protocolMappers:
      - name: "audience resolve"
        protocol: "openid-connect"
        protocolMapper: "oidc-audience-resolve-mapper"
      - name: "realm roles"
        protocol: "openid-connect"
        protocolMapper: "oidc-usermodel-realm-role-mapper"
        config:
          claim.name: "realm_access.roles"
          multivalued: "true"
          access.token.claim: "true"
          id.token.claim: "true"
          userinfo.token.claim: "true"
      - name: "client roles"
        protocol: "openid-connect"
        protocolMapper: "oidc-usermodel-client-role-mapper"
        config:
          claim.name: "resource_access.${client_id}.roles"
          multivalued: "true"
          access.token.claim: "true"
          id.token.claim: "true"
          userinfo.token.claim: "false"