groups:
  - name: ASSET_MANAGER
    path: /ASSET_MANAGER
    attributes:
      description:
        - Inventar bearbeiten
      atrIntern:
        - false
    realmRoles:
      - SHOW_ASSET_MENU_ITEM
      - MANAGE_ASSET
      - READ_ASSET
  - name: ASSET_VIEWER
    path: /ASSET_VIEWER
    attributes:
      description:
        - Inventar anzeigen
      atrIntern:
        - false
    realmRoles:
      - SHOW_ASSET_MENU_ITEM
      - READ_ASSET
  - name: ASSET_TYPE_MANAGER
    path: /ASSET_TYPE_MANAGER
    attributes:
      description:
        - Inventartyp bearbeiten
      atrIntern:
        - false
    realmRoles:
      - MANAGE_ASSET_TYPE
      - READ_ASSET_TYPE
      - SHOW_ASSET_TYPE_MENU_ITEM
  - name: ASSET_TYPE_VIEWER
    path: /ASSET_TYPE_VIEWER
    attributes:
      description:
        - Inventartyp anzeigen
      atrIntern:
        - false
    realmRoles:
      - READ_ASSET_TYPE
      - SHOW_ASSET_TYPE_MENU_ITEM
  - name: CONFIGURATION_MANAGER
    path: /CONFIGURATION_MANAGER
    attributes:
      description:
        - Konfiguration bearbeiten
      atrIntern:
        - true
    realmRoles:
      - SHOW_CONFIGURATION_MENU_ITEM
  - name: FUNCTIONACCOUNT
    path: /FUNCTIONACCOUNT
    attributes:
      description:
        - boolean isFunctionaccount
      atrIntern:
        - true
    realmRoles:
      - MANAGE_USER
  - name: ORDER_MANAGER
    path: /ORDER_MANAGER
    attributes:
      description:
        - Aufträge bearbeiten
      atrIntern:
        - false
    realmRoles:
      - SHOW_ORDER_MENU_ITEM
      - MANAGE_ORDER
      - READ_ORDER
  - name: ORDER_VIEWER
    path: /ORDER_VIEWER
    attributes:
      description:
        - Aufträge anzeigen
      atrIntern:
        - false
    realmRoles:
      - SHOW_ORDER_MENU_ITEM
      - READ_ORDER
  - name: ORDER_TYPE_MANAGER
    path: /ORDER_TYPE_MANAGER
    attributes:
      description:
        - Auftragstypen bearbeiten
      atrIntern:
        - true
    realmRoles:
      - MANAGE_ORDER_TYPE
      - READ_ORDER_TYPE
      - SHOW_ORDER_TYPE_MENU_ITEM
  - name: ORDER_TYPE_VIEWER
    path: /ORDER_TYPE_VIEWER
    attributes:
      description:
        - Auftragstypen anzeigen
      atrIntern:
        - false
    realmRoles:
      - READ_ORDER_TYPE
      - SHOW_ORDER_TYPE_MENU_ITEM
  - name: PRODUCT_MANAGER
    path: /PRODUCT_MANAGER
    attributes:
      description:
        - Produkte bearbeiten
      atrIntern:
        - false
    realmRoles:
      - MANAGE_PRODUCT
      - SHOW_PRODUCT_MENU_ITEM
      - READ_PRODUCT
  - name: PRODUCT_VIEWER
    path: /PRODUCT_VIEWER
    attributes:
      description:
        - Produkte anzeigen
      atrIntern:
        - false
    realmRoles:
      - SHOW_PRODUCT_MENU_ITEM
      - READ_PRODUCT
  - name: PRODUCT_TYPE_MANAGER
    path: /PRODUCT_TYPE_MANAGER
    attributes:
      description:
        - Produkttypen bearbeiten
      atrIntern:
        - false
    realmRoles:
      - MANAGE_PRODUCT_TYPE
      - SHOW_PRODUCT_TYPE_MENU_ITEM
      - READ_PRODUCT_TYPE
  - name: PRODUCT_TYPE_VIEWER
    path: /PRODUCT_TYPE_VIEWER
    attributes:
      description:
        - Produkttypen anzeigen
      atrIntern:
        - false
    realmRoles:
      - SHOW_PRODUCT_TYPE_MENU_ITEM
      - READ_PRODUCT_TYPE
  - name: USER_GROUP_MANAGER
    path: /USER_GROUP_MANAGER
    attributes:
      description:
        - Benutzergruppen bearbeiten
      atrIntern:
        - false
    realmRoles:
      - MANAGE_USER_GROUP
      - SHOW_USER_GROUP_MENU_ITEM
      - READ_USER_GROUP
  - name: USER_GROUP_VIEWER
    path: /USER_GROUP_VIEWER
    attributes:
      description:
        - Benutzergruppen anzeigen
      atrIntern:
        - false
    realmRoles:
      - SHOW_USER_GROUP_MENU_ITEM
      - READ_USER_GROUP
  - name: USER_MANAGER
    path: /USER_MANAGER
    attributes:
      description:
        - Benutzer bearbeiten
      atrIntern:
        - false
    realmRoles:
      - MANAGE_USER
      - READ_USER
      - SHOW_USER_MENU_ITEM
      - READ_USER_GROUP
  - name: USER_VIEWER
    path: /USER_VIEWER
    attributes:
      description:
        - Benutzer anzeigen
      atrIntern:
        - false
    realmRoles:
      - READ_USER
      - SHOW_USER_MENU_ITEM
      - READ_USER_GROUP
  - name: USER_ROLE_MANAGER
    path: /USER_ROLE_MANAGER
    attributes:
      description:
        - Benutzerrolle bearbeiten
      atrIntern:
        - true
    realmRoles:
      - READ_USER_ROLE
      - MANAGE_USER_ROLE
      - SHOW_USER_ROLE_PANEL
  - name: USER_ROLE_VIEWER
    path: /USER_ROLE_VIEWER
    attributes:
      description:
        - Benutzerrolle anzeigen
      atrIntern:
        - true
    realmRoles:
      - READ_USER_ROLE
      - SHOW_USER_ROLE_PANEL
  - name: APS_MANAGER
    path: /APS_MANAGER
    attributes:
      description:
        - Produktionsplanung bearbeiten
      atrIntern:
        - true
    realmRoles:
      - SHOW_APS_MENU_ITEM
      - SHOW_APS_MODULE_MENU_ITEM
  - name: REPORTING_VIEWER
    path: /REPORTING_VIEWER
    attributes:
      description:
        - Report anzeigen
      atrIntern:
        - false
    realmRoles:
      - SHOW_REPORTING
      - READ_REPORTS
  - name: REPORTING_MANAGER
    path: /REPORTING_MANAGER
    attributes:
      description:
        - Report bearbeiten
      atrIntern:
        - false
    realmRoles:
      - SHOW_REPORTING
      - READ_REPORTS
      - MANAGE_REPORTS
  - name: BI_DASHBOARD_VIEWER
    path: /BI_DASHBOARD_VIEWER
    attributes:
      description:
        - Dashboard anzeigen
      atrIntern:
        - false
    realmRoles:
      - SHOW_BI_DASHBOARD
      - READ_BI_DASHBOARD
  - name: BI_DASHBOARD_MANAGER
    path: /BI_DASHBOARD_MANAGER
    attributes:
      description:
        - Dashboard bearbeiten
      atrIntern:
        - false
    realmRoles:
      - SHOW_BI_DASHBOARD
      - READ_BI_DASHBOARD
      - MANAGE_BI_DASHBOARD
  - name: BATCH_MANAGER
    path: /BATCH_MANAGER
    attributes:
      description:
        - Batch bearbeiten
      atrIntern:
        - true
    realmRoles:
      - RESET_BATCH
      - PLAN_WORKING_TIME_FOR_BATCH
      - SHOW_BATCH_MENU_ITEM
      - CREATE_BATCH
      - SPLIT_BATCH
      - READ_BATCH
      - DELETE_OPERATING_ORDER
      - CHANGE_BATCH_HIERARCHY
      - TRIGGER_IMPORT
  - name: NODERED_VIEWER
    path: /NODERED_VIEWER
    attributes:
      description:
        - NodeRed anzeigen
      atrIntern:
        - false
    realmRoles:
      - SHOW_NODERED_MENU_ITEM
      - READ_NODERED
  - name: NODERED_MANAGER
    path: /NODERED_MANAGER
    attributes:
      description:
        - Adminzugriff auf NodeRed
      atrIntern:
        - false
    realmRoles:
      - SHOW_NODERED_MENU_ITEM
      - MANAGE_NODERED
      - READ_NODERED
