roles:
  realm:
    - name: READ_USER_ROLE
      description: Rollen auslesen
    - name: SHOW_USER_ROLE_PANEL
      description: Kachel für Rollenverwaltung anzeigen
    - name: MANAGE_ASSET_TYPE
      description: Assettypverwaltung (Erstellen, Lesen, Bearbeiten, Löschen)
    - name: SHOW_PRODUCT_TYPE_MENU_ITEM
      description: ""
    - name: READ_PRODUCT
      description: ""
    - name: READ_PRODUCT_TYPE
      description: ""
    - name: MANAGE_USER_GROUP
      description: Benutzergruppenverwaltung (Erstellen, Lesen, Bearbeiten, Löschen)
    - name: READ_ASSET_TYPE
      description: Assettypen auslesen
    - name: MANAGE_ASSET
      description: Assetverwaltung (Erstellen, Lesen, Bearbeiten, Löschen)
    - name: SHOW_DEPARTMENT_DEFAULT
      description: Anzeige des Standard-Departments
    - name: SHOW_USER_MENU_ITEM
      description: Menüpunkt für Benutzerverwaltung anzeigen
    - name: READ_ORDER
      description: Aufträge auslesen
    - name: SHOW_ASSET_TYPE_MENU_ITEM
      description: Menüpunkt für Assettypenverwaltung anzeigen
    - name: READ_ORDER_TYPE
      description: Auftragstypen auslesen
    - name: SHOW_CONFIGURATION_MENU_ITEM
      description: ""
    - name: READ_USER_GROUP
      description: Benutzergruppen lesen
    - name: SHOW_ORDER_MENU_ITEM
      description: Menüpunkt für Auftragsverwaltung anzeigen
    - name: MANAGE_ORDER_TYPE
      description: Auftragstypverwaltung (Erstellen, Lesen, Bearbeiten, Löschen)
    - name: default-roles-smartfactory
      description: ${role_default-roles}
    - name: SHOW_USER_GROUP_MENU_ITEM
      description: Menüpunkt für Benutzergruppenverwaltung anzeigen
    - name: SHOW_ORDER_TYPE_MENU_ITEM
      description: Menüpunkt für Auftragstypenverwaltung anzeigen
    - name: MANAGE_PRODUCT
      description: ""
    - name: MANAGE_PRODUCT_TYPE
      description: ""
    - name: MANAGE_USER
      description: Benutzerverwaltung (Erstellen, Lesen, Bearbeiten, Löschen)
    - name: SHOW_PRODUCT_MENU_ITEM
      description: ""
    - name: uma_authorization
      description: ${role_uma_authorization}
    - name: offline_access
      description: ${role_offline-access}
    - name: READ_USER
      description: Benutzer auslesen
    - name: SHOW_ASSET_MENU_ITEM
      description: Menüpunkt für Assetverwaltung anzeigen
    - name: MANAGE_ORDER
      description: Auftragsverwaltung (Erstellen, Lesen, Bearbeiten, Löschen)
    - name: MANAGE_USER_ROLE
      description: Rollenverwaltung (Erstellen, Lesen, Bearbeiten, Löschen)
    - name: READ_ASSET
      description: Assets auslesen
    - name: SHOW_APS_MODULE_MENU_ITEM
      description: Platzhalter momentan
    - name: SHOW_APS_MENU_ITEM
      description: ""
    - name: DEV
      description: Funktionalitäten, die noch entwickelt werden
    - name: SHOW_REPORTING
      description: Menüpunkt für das Reporting Modul
    - name: READ_REPORTS
      description: Zugriff auf den Document Viewer, das Teil vom Reporting ist.
    - name: MANAGE_REPORTS
      description: Zugriff auf den Document Designer, das Teil vom Reporting ist.
    - name: SHOW_BI_DASHBOARD
      description: Menüpunkt für die Dashboards mit dem BI-Tool
    - name: READ_BI_DASHBOARD
      description: Lesender Zugriff auf die BI-Dashboards
    - name: MANAGE_BI_DASHBOARD
      description: Verwaltung der BI-Dashboards
    - name: PLAN_WORKING_TIME_FOR_BATCH
      description: Start und Ende von Lots/Batches planen und nach AP+ exportieren
    - name: CHANGE_BATCH_HIERARCHY
      description: Batchhierarchie ändern
    - name: RESET_BATCH
      description: Betriebsauftrag zurücksetzen
    - name: SHOW_BATCH_MENU_ITEM
      description: Menüpunkt für Batchbildung anzeigen
    - name: CREATE_BATCH
      description: Erstellen eines Batches bzw. Zusammenführen von Werkstattaufträgen
    - name: SPLIT_BATCH
      description: Aufteilen eines Batches in seine Werkstattaufträge
    - name: DELETE_OPERATING_ORDER
      description: Löschen aller Batches und Werkstattaufträge von einem Betriebsauftrag
    - name: READ_BATCH
      description: Lesen von Batches und Werkstattaufträgen und deren Maschinengruppen
    - name: TRIGGER_IMPORT
      description: Import von Daten aus AP Schnittstelle starten
    - name: SHOW_NODERED_MENU_ITEM
      description: Menüpunkt für NodeRed anzeigen
    - name: MANAGE_NODERED
      description: Vollzugriff auf NodeRed (View, Edit, Deploy)
    - name: READ_NODERED
      description: Nodered Flow anzeigen
